language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t anupkhandelwal/docker-web -f Dockerfile.dev .

script:
  - docker run -e CI=true anupkhandelwal/docker-web npm run test

  deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-web"
    env: "DockerWeb-env"
    bucket_name: "elasticbeanstalk-ap-south-1-909815893518"
    bucket_path: "docker-web"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY    